// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: beacon.proto

package beacon

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BeaconIncoming struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Location  string         `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	Platform  string         `protobuf:"bytes,3,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Range     string         `protobuf:"bytes,4,opt,name=Range,proto3" json:"Range,omitempty"`
	Pwd       string         `protobuf:"bytes,5,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Executors *ListOfStrings `protobuf:"bytes,6,opt,name=Executors,proto3" json:"Executors,omitempty"`
	Links     *Links         `protobuf:"bytes,7,opt,name=Links,proto3" json:"Links,omitempty"`
}

func (x *BeaconIncoming) Reset() {
	*x = BeaconIncoming{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconIncoming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconIncoming) ProtoMessage() {}

func (x *BeaconIncoming) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconIncoming.ProtoReflect.Descriptor instead.
func (*BeaconIncoming) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *BeaconIncoming) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeaconIncoming) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BeaconIncoming) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BeaconIncoming) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *BeaconIncoming) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *BeaconIncoming) GetExecutors() *ListOfStrings {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *BeaconIncoming) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type BeaconOutgoing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Location  string         `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	Platform  string         `protobuf:"bytes,3,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Range     string         `protobuf:"bytes,4,opt,name=Range,proto3" json:"Range,omitempty"`
	Pwd       string         `protobuf:"bytes,5,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Executors *ListOfStrings `protobuf:"bytes,6,opt,name=Executors,proto3" json:"Executors,omitempty"`
	Links     *Links         `protobuf:"bytes,7,opt,name=Links,proto3" json:"Links,omitempty"`
}

func (x *BeaconOutgoing) Reset() {
	*x = BeaconOutgoing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconOutgoing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconOutgoing) ProtoMessage() {}

func (x *BeaconOutgoing) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconOutgoing.ProtoReflect.Descriptor instead.
func (*BeaconOutgoing) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{1}
}

func (x *BeaconOutgoing) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeaconOutgoing) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BeaconOutgoing) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BeaconOutgoing) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *BeaconOutgoing) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *BeaconOutgoing) GetExecutors() *ListOfStrings {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *BeaconOutgoing) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type ListOfStrings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strings []string `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
}

func (x *ListOfStrings) Reset() {
	*x = ListOfStrings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfStrings) ProtoMessage() {}

func (x *ListOfStrings) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfStrings.ProtoReflect.Descriptor instead.
func (*ListOfStrings) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{2}
}

func (x *ListOfStrings) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

type Links struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Ttp      string `protobuf:"bytes,2,opt,name=ttp,proto3" json:"ttp,omitempty"`
	Tactic   string `protobuf:"bytes,3,opt,name=tactic,proto3" json:"tactic,omitempty"`
	Executor string `protobuf:"bytes,4,opt,name=Executor,proto3" json:"Executor,omitempty"`
	Request  string `protobuf:"bytes,5,opt,name=Request,proto3" json:"Request,omitempty"`
	Response string `protobuf:"bytes,6,opt,name=Response,proto3" json:"Response,omitempty"`
	Payload  string `protobuf:"bytes,7,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *Links) Reset() {
	*x = Links{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beacon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_beacon_proto_rawDescGZIP(), []int{3}
}

func (x *Links) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Links) GetTtp() string {
	if x != nil {
		return x.Ttp
	}
	return ""
}

func (x *Links) GetTactic() string {
	if x != nil {
		return x.Tactic
	}
	return ""
}

func (x *Links) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Links) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *Links) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *Links) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_beacon_proto protoreflect.FileDescriptor

var file_beacon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x22, 0xde, 0x01, 0x0a, 0x0e, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50,
	0x77, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x12, 0x33, 0x0a,
	0x09, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x09, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x52, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0xde, 0x01, 0x0a, 0x0e, 0x42, 0x65, 0x61, 0x63,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x50, 0x77, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x12, 0x33,
	0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x09, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x73, 0x52, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x74, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x63, 0x74, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x63, 0x74, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x32, 0x44, 0x0a, 0x06, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x3a, 0x0a,
	0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x1a,
	0x16, 0x2e, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4f,
	0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x4c, 0x0a, 0x06, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x42, 0x0b, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x2d, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x2f, 0x62, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0xa2, 0x02, 0x03, 0x48, 0x4c, 0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beacon_proto_rawDescOnce sync.Once
	file_beacon_proto_rawDescData = file_beacon_proto_rawDesc
)

func file_beacon_proto_rawDescGZIP() []byte {
	file_beacon_proto_rawDescOnce.Do(func() {
		file_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(file_beacon_proto_rawDescData)
	})
	return file_beacon_proto_rawDescData
}

var file_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_beacon_proto_goTypes = []interface{}{
	(*BeaconIncoming)(nil), // 0: beacon.BeaconIncoming
	(*BeaconOutgoing)(nil), // 1: beacon.BeaconOutgoing
	(*ListOfStrings)(nil),  // 2: beacon.ListOfStrings
	(*Links)(nil),          // 3: beacon.Links
}
var file_beacon_proto_depIdxs = []int32{
	2, // 0: beacon.BeaconIncoming.Executors:type_name -> beacon.ListOfStrings
	3, // 1: beacon.BeaconIncoming.Links:type_name -> beacon.Links
	2, // 2: beacon.BeaconOutgoing.Executors:type_name -> beacon.ListOfStrings
	3, // 3: beacon.BeaconOutgoing.Links:type_name -> beacon.Links
	0, // 4: beacon.Beacon.Handle:input_type -> beacon.BeaconIncoming
	1, // 5: beacon.Beacon.Handle:output_type -> beacon.BeaconOutgoing
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_beacon_proto_init() }
func file_beacon_proto_init() {
	if File_beacon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beacon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconIncoming); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beacon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconOutgoing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beacon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfStrings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beacon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Links); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beacon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_proto_goTypes,
		DependencyIndexes: file_beacon_proto_depIdxs,
		MessageInfos:      file_beacon_proto_msgTypes,
	}.Build()
	File_beacon_proto = out.File
	file_beacon_proto_rawDesc = nil
	file_beacon_proto_goTypes = nil
	file_beacon_proto_depIdxs = nil
}
